version: '2'

services:
  db:
    image: mysql:5
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/Data/mysql:/var/lib/mysql
  web:
    build: .
    container_name: myweb
    ports:
      - "5000:5000"
    links:
      - db:flask